# Copyright (C) 2017 Kazumasa Kohtaka <kkohtaka@gmail.com> All right reserved
# This file is available under the MIT license.

- name: Add APT repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt_repositories }}"
