# Copyright (C) 2017 Kazumasa Kohtaka <kkohtaka@gmail.com> All right reserved
# This file is available under the MIT license.

- hosts: localhost
  connection: local
  become: yes
  roles:
  - add-apt-repositories
  - add-apt-packages
  - add-pip-packages
  - add-docker-ce
  - add-tensorflow-c-library
  - add-google-cloud-sdk
  - add-kubernetes

- hosts: localhost
  connection: local
  roles:
  - add-binaries
